name: newest_shadowing_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  scidart: ^0.0.1
  flutter_dotenv: ^5.0.2
  path_provider: ^2.1.1
  flutter_sound: ^9.24.4
  provider: ^6.1.2
  audioplayers: ^6.1.2  # ✅ 最新版
  record: ^5.2.1
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.4.9
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3
  custom_painter: ^1.0.0
  fl_chart: ^0.70.2
  syncfusion_flutter_sliders: ^28.2.5  
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  googleapis: ^13.1.0  # 最新バージョンを確認してね
  googleapis_auth: 
  logger: ^2.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/.env
    - assets/mount_fuji.mp3



  uses-material-design: true

